# This workflow automatically applies labels to GitHub issues and pull requests based on the
# file paths in a pull request or content in the body of an issue or pull request.
#
# NOTE: This file is automatically synchronized from Mu DevOps. Update the original file there
#       instead of the file in this repo.
#
# NOTE: This file uses a reusable workflow. Do not make changes to the file that should be made
#       in the common/reusable workflow.
#
# - Mu DevOps Repo: https://github.com/microsoft/mu_devops
# - File Sync Settings: https://github.com/microsoft/mu_devops/blob/main/.sync/Files.yml
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
#

name: Apply Issue and PR Labels 2

on:
  issues:
    types:
      - edited
      - opened
  pull_request_target:
    types:
      - edited
      - opened
      - reopened
      - synchronize
  workflow_dispatch:
  workflow_call:

jobs:
  sync:
    name: Label Based on Messages
    runs-on: ubuntu-latest

    steps:
      - name: Generate Token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.MU_ACCESS_APP_ID }}
          private-key: ${{ secrets.MU_ACCESS_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Apply Labels Based on PR File Paths
        uses: actions/labeler@v6.0.1
        with:
          configuration-path: .github/workflows/label-issues/file-paths.yml
          repo-token: ${{ steps.app-token.outputs.token }}
          sync-labels: true
        if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'

      - name: Apply PR Labels Based on Policies
        uses: srvaroa/labeler@v1.13.0
        with:
          config_path: .github/workflows/label-issues/regex-pull-requests.yml
          use_local_config: false
          fail_on_error: true
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
