[package]
name = "user-sp-entry-lib"
categories = ["embedded", "no-std"]
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "Provides user space entry services"
readme = "README.md"
keywords = ["embedded", "no-std", "boot", "firmware"]

[package.metadata.docs.rs]
targets = ["aarch64-unknown-none", "aarch64-unknown-none-softfloat"]

[dependencies]
uuid.workspace = true
odp-ffa.workspace = true
ec-service-lib.workspace = true

[features]
default = []
